import axios from 'axios';

/**
 * Smart local AI engine - generates data-driven recommendations
 * without any external API key. Used as fallback or demo mode.
 */
const generateLocalRecommendation = (employees) => {
  // Sort employees by a composite score (performance 70% + experience 30%)
  const ranked = [...employees]
    .map(emp => ({
      ...emp,
      compositeScore: (emp.performanceScore * 0.7) + (Math.min(emp.experience, 15) * (100 / 15) * 0.3)
    }))
    .sort((a, b) => b.compositeScore - a.compositeScore);

  const promotionCandidates = ranked.filter(e => e.performanceScore >= 80 && e.experience >= 2);
  const needsTraining = ranked.filter(e => e.performanceScore < 70);

  let report = `# 🤖 EvoHR AI Strategic Performance Report\n\n`;
  report += `> *Generated by EvoHR Smart Analytics Engine — Based on ${employees.length} employee profile(s)*\n\n---\n\n`;

  // Section 1: Promotion Recommendations
  report += `## 🏆 1. Promotion Recommendations\n\n`;
  if (promotionCandidates.length > 0) {
    promotionCandidates.forEach((emp, i) => {
      const medal = i === 0 ? '🥇' : i === 1 ? '🥈' : '🥉';
      report += `### ${medal} ${emp.name} — **Strongly Recommended**\n`;
      report += `- **Performance Score:** ${emp.performanceScore}/100\n`;
      report += `- **Experience:** ${emp.experience} year(s)\n`;
      report += `- **Department:** ${emp.department}\n`;
      report += `- **Justification:** ${emp.name} has demonstrated exceptional performance with a score of ${emp.performanceScore}% and ${emp.experience} year(s) of solid experience in ${emp.department}. They show strong leadership potential and readiness for the next level.\n\n`;
    });
  } else {
    report += `*No employees currently meet the promotion threshold (Score ≥ 80, Experience ≥ 2 years). Focus on skill development and performance improvement.*\n\n`;
  }

  report += `---\n\n`;

  // Section 2: Employee Rankings
  report += `## 📊 2. Employee Rankings (Performance Matrix)\n\n`;
  report += `| Rank | Name | Department | Score | Experience | Composite Index | Status |\n`;
  report += `|------|------|-----------|-------|------------|----------------|--------|\n`;

  ranked.forEach((emp, i) => {
    const rank = i === 0 ? '🥇 #1' : i === 1 ? '🥈 #2' : i === 2 ? '🥉 #3' : `#${i + 1}`;
    const status = emp.performanceScore >= 85 ? '🟢 Excellent' : emp.performanceScore >= 70 ? '🔵 Good' : emp.performanceScore >= 55 ? '🟡 Average' : '🔴 Needs Help';
    report += `| ${rank} | **${emp.name}** | ${emp.department} | ${emp.performanceScore}/100 | ${emp.experience} yrs | ${emp.compositeScore.toFixed(1)} | ${status} |\n`;
  });

  report += `\n---\n\n`;

  // Section 3: Training Suggestions
  report += `## 📚 3. Personalized Training Suggestions\n\n`;
  employees.forEach(emp => {
    report += `### 👤 ${emp.name} (${emp.department})\n`;
    const currentSkills = emp.skills || [];
    report += `**Current Skills:** ${currentSkills.length > 0 ? currentSkills.join(', ') : 'Not specified'}\n\n`;

    const suggestions = [];
    if (emp.performanceScore < 70) suggestions.push('🎯 **Performance Coaching Program** — Enroll in a structured mentorship program to identify and address performance gaps.');
    if (emp.experience < 2) suggestions.push('📖 **Foundation Training Track** — Focus on building core domain expertise through structured learning paths.');
    if (!currentSkills.some(s => /leadership|manage|lead/i.test(s)) && emp.experience >= 3) suggestions.push('🌟 **Leadership & Management Skills** — Develop team leadership capabilities for future managerial roles.');
    if (!currentSkills.some(s => /communication|present/i.test(s))) suggestions.push('🗣️ **Communication & Presentation Skills** — Enhance professional communication for better cross-team collaboration.');
    if (emp.department === 'Engineering' && !currentSkills.some(s => /agile|scrum/i.test(s))) suggestions.push('⚙️ **Agile & Scrum Certification** — Master agile methodology to improve project delivery speed.');
    if (emp.department === 'Marketing' && !currentSkills.some(s => /seo|analytics|digital/i.test(s))) suggestions.push('📈 **Digital Marketing & Analytics** — Learn data-driven marketing tools like Google Analytics and SEO.');
    if (emp.department === 'Design' && !currentSkills.some(s => /figma|ux|ui/i.test(s))) suggestions.push('🎨 **Advanced UI/UX Design (Figma)** — Upskill in modern design tools and user experience principles.');
    if (suggestions.length === 0) suggestions.push('🔭 **Advanced Domain Specialization** — Pursue specialized certifications in your field to stay ahead of industry trends.');

    suggestions.forEach(s => report += `- ${s}\n`);
    report += '\n';
  });

  report += `---\n\n`;

  // Section 4: AI Feedback
  report += `## 💡 4. Personalized AI Feedback\n\n`;
  ranked.forEach(emp => {
    report += `### 📝 ${emp.name}\n`;
    let feedback = '';
    if (emp.performanceScore >= 85) {
      feedback = `**Outstanding performance!** ${emp.name} is a top-tier asset to the ${emp.department} team. With a score of ${emp.performanceScore}/100 and ${emp.experience} year(s) of experience, you are setting a benchmark for excellence. Keep pushing boundaries — your growth trajectory is impressive and you are on the fast track to leadership roles. 🚀`;
    } else if (emp.performanceScore >= 70) {
      feedback = `**Good work, ${emp.name}!** A performance score of ${emp.performanceScore}/100 shows consistent delivery and reliability. To reach the next level, focus on going beyond the basics — take ownership of challenging projects and build deeper expertise in your key skills. The gap to excellence is small and achievable. 💪`;
    } else if (emp.performanceScore >= 55) {
      feedback = `**Keep going, ${emp.name}!** A score of ${emp.performanceScore}/100 shows you have a foundation to build on. Every expert was once a beginner. Identify your biggest performance gaps, seek mentorship, and commit to daily improvement. With focused effort, significant progress is just weeks away. 🌱`;
    } else {
      feedback = `**Time for a turnaround, ${emp.name}.** A score of ${emp.performanceScore}/100 signals that immediate action is needed. This is not a setback — it's an opportunity to reset and rebuild. Work closely with your manager to create a clear improvement plan with weekly milestones. You have the potential, now channel it with focus. 🔥`;
    }
    report += `${feedback}\n\n`;
  });

  report += `---\n*Report generated on ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })} by EvoHR Smart Analytics Engine*`;
  return report;
};


export const getAIRecommendation = async (req, res) => {
  try {
    const { employees } = req.body;

    if (!employees || employees.length === 0) {
      return res.status(400).json({ message: 'Please provide employee data for recommendations' });
    }

    const apiKey = process.env.AI_API_KEY;
    const apiUrl = process.env.AI_API_URL || 'https://openrouter.ai/api/v1/chat/completions';

    // If no API key configured, use the smart local engine
    if (!apiKey || apiKey === 'your_openrouter_api_key_here') {
      console.log('No AI API key found — using local smart recommendation engine.');
      const recommendation = generateLocalRecommendation(employees);
      return res.json({ recommendation, source: 'local' });
    }

    // Use external AI API if key is present
    const prompt = `You are an expert HR analytics AI. Analyze the following employee performance data and provide a comprehensive strategic report with these 4 sections:

## 1. 🏆 Promotion Recommendations
List employees who should be promoted and clearly explain why.

## 2. 📊 Employee Rankings
Rank ALL employees from highest to lowest using: performance score (70%) + experience (30%).

## 3. 📚 Training Suggestions
For each employee, suggest specific skills or training they need.

## 4. 💡 AI Feedback
Provide personalized motivational feedback for each employee.

Employee Data:
${JSON.stringify(employees, null, 2)}

Be specific, data-driven, and use actual employee names and scores.`;

    const response = await axios.post(
      apiUrl,
      {
        model: process.env.AI_MODEL || 'mistralai/mistral-7b-instruct:free',
        messages: [{ role: 'user', content: prompt }],
        max_tokens: 2000,
      },
      {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
          'HTTP-Referer': 'http://localhost:5173',
          'X-Title': 'EvoHR Employee Performance System',
        },
        timeout: 30000,
      }
    );

    const recommendation = response.data.choices[0].message.content;
    return res.json({ recommendation, source: 'openrouter' });

  } catch (error) {
    console.error('AI Error:', error.response?.data || error.message);

    // Fallback to local engine if API fails
    console.log('API failed — falling back to local smart engine.');
    try {
      const recommendation = generateLocalRecommendation(req.body.employees);
      return res.json({ recommendation, source: 'local-fallback' });
    } catch (localError) {
      return res.status(500).json({ message: 'Failed to generate recommendations. Please try again.' });
    }
  }
};
